/**
 * Comprehensive Indian Railway Stations Database
 * Major Stations, Junctions, Terminals & Divisions across India
 */

export const INDIAN_STATIONS = [
  { code: 'NDLS', name: 'New Delhi', state: 'Delhi' },
  { code: 'DLI', name: 'Old Delhi Junction', state: 'Delhi' },
  { code: 'NZM', name: 'Hazrat Nizamuddin', state: 'Delhi' },
  { code: 'ANVT', name: 'Anand Vihar Terminal', state: 'Delhi' },
  { code: 'DEC', name: 'Delhi Cantt', state: 'Delhi' },
  { code: 'DEE', name: 'Delhi Sarai Rohilla', state: 'Delhi' },
  { code: 'CSMT', name: 'Mumbai Chhatrapati Shivaji Maharaj Terminus', state: 'Maharashtra' },
  { code: 'MMCT', name: 'Mumbai Central', state: 'Maharashtra' },
  { code: 'BDTS', name: 'Bandra Terminus', state: 'Maharashtra' },
  { code: 'LTT', name: 'Lokmanya Tilak Terminus (Kurla)', state: 'Maharashtra' },
  { code: 'DR', name: 'Dadar Central', state: 'Maharashtra' },
  { code: 'PUNE', name: 'Pune Junction', state: 'Maharashtra' },
  { code: 'NGP', name: 'Nagpur Junction', state: 'Maharashtra' },
  { code: 'SUR', name: 'Solapur Junction', state: 'Maharashtra' },
  { code: 'KOP', name: 'Kolhapur CSMT', state: 'Maharashtra' },
  { code: 'NK', name: 'Nashik Road', state: 'Maharashtra' },
  { code: 'BSL', name: 'Bhusawal Junction', state: 'Maharashtra' },
  { code: 'AWB', name: 'Aurangabad', state: 'Maharashtra' },
  { code: 'HWH', name: 'Howrah Junction', state: 'West Bengal' },
  { code: 'SDAH', name: 'Sealdah', state: 'West Bengal' },
  { code: 'KOAA', name: 'Kolkata Chitpur Terminal', state: 'West Bengal' },
  { code: 'SHM', name: 'Shalimar', state: 'West Bengal' },
  { code: 'KGP', name: 'Kharagpur Junction', state: 'West Bengal' },
  { code: 'ASN', name: 'Asansol Junction', state: 'West Bengal' },
  { code: 'NJP', name: 'New Jalpaiguri (Siliguri)', state: 'West Bengal' },
  { code: 'MLDT', name: 'Malda Town', state: 'West Bengal' },
  { code: 'MAS', name: 'Chennai Central (Puratchi Thalaivar Dr. MGR)', state: 'Tamil Nadu' },
  { code: 'MS', name: 'Chennai Egmore', state: 'Tamil Nadu' },
  { code: 'TBM', name: 'Tambaram (Chennai)', state: 'Tamil Nadu' },
  { code: 'CBE', name: 'Coimbatore Junction', state: 'Tamil Nadu' },
  { code: 'MDU', name: 'Madurai Junction', state: 'Tamil Nadu' },
  { code: 'TPJ', name: 'Tiruchchirappalli Junction', state: 'Tamil Nadu' },
  { code: 'SA', name: 'Salem Junction', state: 'Tamil Nadu' },
  { code: 'ED', name: 'Erode Junction', state: 'Tamil Nadu' },
  { code: 'TEN', name: 'Tirunelveli Junction', state: 'Tamil Nadu' },
  { code: 'RMM', name: 'Rameswaram', state: 'Tamil Nadu' },
  { code: 'CAPE', name: 'Kanyakumari', state: 'Tamil Nadu' },
  { code: 'SBC', name: 'KSR Bengaluru City', state: 'Karnataka' },
  { code: 'YPR', name: 'Yesvantpur Junction (Bengaluru)', state: 'Karnataka' },
  { code: 'SMVB', name: 'Sir M. Visvesvaraya Terminal (Bengaluru)', state: 'Karnataka' },
  { code: 'MYS', name: 'Mysuru Junction', state: 'Karnataka' },
  { code: 'UBL', name: 'SSS Hubballi Junction', state: 'Karnataka' },
  { code: 'MAQ', name: 'Mangaluru Central', state: 'Karnataka' },
  { code: 'MAJN', name: 'Mangaluru Junction', state: 'Karnataka' },
  { code: 'BGM', name: 'Belagavi', state: 'Karnataka' },
  { code: 'KLBG', name: 'Kalaburagi (Gulbarga)', state: 'Karnataka' },
  { code: 'BAY', name: 'Ballari Junction', state: 'Karnataka' },
  { code: 'ADI', name: 'Ahmedabad Junction', state: 'Gujarat' },
  { code: 'BRC', name: 'Vadodara Junction', state: 'Gujarat' },
  { code: 'ST', name: 'Surat', state: 'Gujarat' },
  { code: 'RJT', name: 'Rajkot Junction', state: 'Gujarat' },
  { code: 'GIMB', name: 'Gandhidham Junction', state: 'Gujarat' },
  { code: 'BVC', name: 'Bhavnagar Terminus', state: 'Gujarat' },
  { code: 'JAM', name: 'Jamnagar', state: 'Gujarat' },
  { code: 'DWK', name: 'Dwarka', state: 'Gujarat' },
  { code: 'PNBE', name: 'Patna Junction', state: 'Bihar' },
  { code: 'DNR', name: 'Danapur', state: 'Bihar' },
  { code: 'PPTA', name: 'Patliputra Junction', state: 'Bihar' },
  { code: 'GAYA', name: 'Gaya Junction', state: 'Bihar' },
  { code: 'MFP', name: 'Muzaffarpur Junction', state: 'Bihar' },
  { code: 'DBG', name: 'Darbhanga Junction', state: 'Bihar' },
  { code: 'BJU', name: 'Barauni Junction', state: 'Bihar' },
  { code: 'KIR', name: 'Katihar Junction', state: 'Bihar' },
  { code: 'BGP', name: 'Bhagalpur Junction', state: 'Bihar' },
  { code: 'SHC', name: 'Saharsa Junction', state: 'Bihar' },
  { code: 'BSB', name: 'Varanasi Junction', state: 'Uttar Pradesh' },
  { code: 'BSBS', name: 'Banaras', state: 'Uttar Pradesh' },
  { code: 'DDU', name: 'Pt. Deen Dayal Upadhyaya Junction (Mughalsarai)', state: 'Uttar Pradesh' },
  { code: 'LKO', name: 'Lucknow Charbagh NR', state: 'Uttar Pradesh' },
  { code: 'LJN', name: 'Lucknow Junction NER', state: 'Uttar Pradesh' },
  { code: 'CNB', name: 'Kanpur Central', state: 'Uttar Pradesh' },
  { code: 'PRYJ', name: 'Prayagraj Junction (Allahabad)', state: 'Uttar Pradesh' },
  { code: 'AGC', name: 'Agra Cantt', state: 'Uttar Pradesh' },
  { code: 'AF', name: 'Agra Fort', state: 'Uttar Pradesh' },
  { code: 'GKP', name: 'Gorakhpur Junction', state: 'Uttar Pradesh' },
  { code: 'MB', name: 'Moradabad Junction', state: 'Uttar Pradesh' },
  { code: 'BE', name: 'Bareilly Junction', state: 'Uttar Pradesh' },
  { code: 'MTC', name: 'Meerut City', state: 'Uttar Pradesh' },
  { code: 'GZB', name: 'Ghaziabad Junction', state: 'Uttar Pradesh' },
  { code: 'AY', name: 'Ayodhya Dham Junction', state: 'Uttar Pradesh' },
  { code: 'AYC', name: 'Ayodhya Cantt', state: 'Uttar Pradesh' },
  { code: 'MTJ', name: 'Mathura Junction', state: 'Uttar Pradesh' },
  { code: 'VGLJ', name: 'Virangana Lakshmibai Jhansi', state: 'Uttar Pradesh' },
  { code: 'HYB', name: 'Hyderabad Deccan (Nampally)', state: 'Telangana' },
  { code: 'SC', name: 'Secunderabad Junction', state: 'Telangana' },
  { code: 'KCG', name: 'Kacheguda (Hyderabad)', state: 'Telangana' },
  { code: 'KZJ', name: 'Kazipet Junction', state: 'Telangana' },
  { code: 'WL', name: 'Warangal', state: 'Telangana' },
  { code: 'BZA', name: 'Vijayawada Junction', state: 'Andhra Pradesh' },
  { code: 'VSKP', name: 'Visakhapatnam Junction', state: 'Andhra Pradesh' },
  { code: 'TPTY', name: 'Tirupati Main', state: 'Andhra Pradesh' },
  { code: 'RU', name: 'Renigunta Junction', state: 'Andhra Pradesh' },
  { code: 'GNT', name: 'Guntur Junction', state: 'Andhra Pradesh' },
  { code: 'RJY', name: 'Rajahmundry', state: 'Andhra Pradesh' },
  { code: 'BPL', name: 'Bhopal Junction', state: 'Madhya Pradesh' },
  { code: 'RKMP', name: 'Rani Kamlapati (Habibganj)', state: 'Madhya Pradesh' },
  { code: 'INDB', name: 'Indore Junction', state: 'Madhya Pradesh' },
  { code: 'JBP', name: 'Jabalpur Junction', state: 'Madhya Pradesh' },
  { code: 'GWL', name: 'Gwalior Junction', state: 'Madhya Pradesh' },
  { code: 'UJN', name: 'Ujjain Junction', state: 'Madhya Pradesh' },
  { code: 'RTM', name: 'Ratlam Junction', state: 'Madhya Pradesh' },
  { code: 'KOTA', name: 'Kota Junction', state: 'Rajasthan' },
  { code: 'JP', name: 'Jaipur Junction', state: 'Rajasthan' },
  { code: 'JU', name: 'Jodhpur Junction', state: 'Rajasthan' },
  { code: 'BKN', name: 'Bikaner Junction', state: 'Rajasthan' },
  { code: 'AII', name: 'Ajmer Junction', state: 'Rajasthan' },
  { code: 'UDZ', name: 'Udaipur City', state: 'Rajasthan' },
  { code: 'ABR', name: 'Abu Road', state: 'Rajasthan' },
  { code: 'BBS', name: 'Bhubaneswar', state: 'Odisha' },
  { code: 'PURI', name: 'Puri', state: 'Odisha' },
  { code: 'CTC', name: 'Cuttack Junction', state: 'Odisha' },
  { code: 'ROU', name: 'Rourkela Junction', state: 'Odisha' },
  { code: 'SBP', name: 'Sambalpur Junction', state: 'Odisha' },
  { code: 'RNC', name: 'Ranchi Junction', state: 'Jharkhand' },
  { code: 'DHN', name: 'Dhanbad Junction', state: 'Jharkhand' },
  { code: 'TATA', name: 'Tatanagar Junction (Jamshedpur)', state: 'Jharkhand' },
  { code: 'JSME', name: 'Jasidih Junction (Deoghar)', state: 'Jharkhand' },
  { code: 'GHY', name: 'Guwahati', state: 'Assam' },
  { code: 'KYQ', name: 'Kamakhya Junction', state: 'Assam' },
  { code: 'DBRG', name: 'Dibrugarh', state: 'Assam' },
  { code: 'SCL', name: 'Silchar', state: 'Assam' },
  { code: 'TVC', name: 'Thiruvananthapuram Central', state: 'Kerala' },
  { code: 'ERS', name: 'Ernakulam Junction (South)', state: 'Kerala' },
  { code: 'ERN', name: 'Ernakulam Town (North)', state: 'Kerala' },
  { code: 'CLT', name: 'Kozhikode Main (Calicut)', state: 'Kerala' },
  { code: 'TCR', name: 'Thrissur', state: 'Kerala' },
  { code: 'CAN', name: 'Kannur', state: 'Kerala' },
  { code: 'QLN', name: 'Kollam Junction', state: 'Kerala' },
  { code: 'ASR', name: 'Amritsar Junction', state: 'Punjab' },
  { code: 'LDH', name: 'Ludhiana Junction', state: 'Punjab' },
  { code: 'JUC', name: 'Jalandhar City', state: 'Punjab' },
  { code: 'CDG', name: 'Chandigarh Junction', state: 'Chandigarh' },
  { code: 'UMB', name: 'Ambala Cantt Junction', state: 'Haryana' },
  { code: 'KLK', name: 'Kalka', state: 'Haryana' },
  { code: 'JAT', name: 'Jammu Tawi', state: 'Jammu & Kashmir' },
  { code: 'SVDK', name: 'Shri Mata Vaishno Devi Katra', state: 'Jammu & Kashmir' },
  { code: 'DDN', name: 'Dehradun', state: 'Uttarakhand' },
  { code: 'HW', name: 'Haridwar Junction', state: 'Uttarakhand' },
  { code: 'KGM', name: 'Kathgodam', state: 'Uttarakhand' },
  { code: 'R', name: 'Raipur Junction', state: 'Chhattisgarh' },
  { code: 'BSP', name: 'Bilaspur Junction', state: 'Chhattisgarh' },
  { code: 'DURG', name: 'Durg Junction', state: 'Chhattisgarh' },
  { code: 'MAO', name: 'Madgaon Junction (Goa)', state: 'Goa' },
  { code: 'KRMI', name: 'Karmali (Goa)', state: 'Goa' },
  { code: 'VSG', name: 'Vasco-da-Gama', state: 'Goa' }
];

export function populateStationDatalist(datalistId = 'stations-list') {
  const datalist = document.getElementById(datalistId);
  if (!datalist) return;
  datalist.innerHTML = '';
  INDIAN_STATIONS.forEach(stn => {
    const opt = document.createElement('option');
    opt.value = `${stn.code} - ${stn.name} (${stn.state})`;
    datalist.appendChild(opt);
  });
}
